version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: nl2sql-postgres
    environment:
      POSTGRES_DB: sales_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./cube/data:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d sales_analytics" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  cube:
    image: cubejs/cube:latest
    container_name: nl2sql-cube
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./cube/model:/cube/conf/model
    environment:
      CUBEJS_DEV_MODE: "true"
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_HOST: postgres
      CUBEJS_DB_PORT: 5432
      CUBEJS_DB_NAME: sales_analytics
      CUBEJS_DB_USER: postgres
      CUBEJS_DB_PASS: postgres
      CUBEJS_API_SECRET: mysecretkey123

volumes:
  postgres_data:
