name: nl2sql
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: sales_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./cube/data:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d sales_data" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 40s

  cube:
    restart: always
    image: cubejs/cube:latest
    ports:
      - "4000:4000"
    environment:
      CUBEJS_DEV_MODE: "true"
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_HOST: postgres
      CUBEJS_DB_NAME: sales_data
      CUBEJS_DB_USER: postgres
      CUBEJS_DB_PASS: postgres
      CUBEJS_API_SECRET: mysecretkey123
      CUBEJS_DB_CONNECT_TIMEOUT: 60000
      CUBEJS_DB_MAX_POOL_SIZE: 10
    volumes:
      - ./cube/model:/cube/conf/model
    depends_on:
      postgres:
        condition: service_healthy

  catalog-generator:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app
    command: >
      sh -c "pip install pyyaml && python backend/app/utils/generate_catalog.py"
    depends_on:
      - cube
    restart: "no"

volumes:
  postgres_data:
