services:
  postgres:
    image: postgres:15
    container_name: nl2sql-postgres
    environment:
      POSTGRES_DB: sales_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./cube/data/01_source_db.sql:/docker-entrypoint-initdb.d/01_source_db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d sales_analytics" ]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 30s

  cube:
    image: cubejs/cube:latest
    container_name: nl2sql-cube
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./cube/model:/cube/conf/model
    environment:
      CUBEJS_DEV_MODE: "true"
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_HOST: postgres
      CUBEJS_DB_PORT: 5432
      CUBEJS_DB_NAME: sales_analytics
      CUBEJS_DB_USER: postgres
      CUBEJS_DB_PASS: postgres
      CUBEJS_API_SECRET: mysecretkey123
      CUBEJS_DB_CONNECT_TIMEOUT: 120000

  redis:
    image: redis:7-alpine
    container_name: nl2sql-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
