services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: sales_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d

  cube:
    restart: always
    image: cubejs/cube:latest
    ports:
      - "4000:4000"
    environment:
      CUBEJS_DEV_MODE: "true"
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_HOST: postgres
      CUBEJS_DB_NAME: sales_data
      CUBEJS_DB_USER: postgres
      CUBEJS_DB_PASS: postgres
      CUBEJS_API_SECRET: mysecretkey123
    volumes:
      - ./model:/cube/conf/model
    depends_on:
      - postgres

volumes:
  postgres_data:
